part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const home = _Paths.home;
  static const splash = _Paths.splash;
  static const onboarding = _Paths.onboarding;
  static const login = _Paths.login;
  static const signUP = _Paths.signUP;
  static const forgotPassword = _Paths.forgotPassword;
  static const verifyOtp = _Paths.verifyOtp;
  static const resetPassword = _Paths.resetPassword;
  static const bottomNav = _Paths.bottomNav;
  static const messages = _Paths.messages;
  static const saved = _Paths.saved;
  static const category = _Paths.category;
  static const profile = _Paths.profile;
  static const searchProductView = _Paths.searchProductView;
  static const recommendedProductView = _Paths.recommendedProductView;
  static const trendingProductsView = _Paths.trendingProductsView;
  static const searchLocation = _Paths.searchLocation;
  static const productDetails = _Paths.productDetails;
  static const reviews = _Paths.reviews;
  static const store = _Paths.store;
  static const myCart = _Paths.myCart;
  static const checkoutView = _Paths.checkoutView;
  static const checkoutSuccessfulView = _Paths.checkoutSuccessfulView;
  static const notification = _Paths.notification;
  static const shopByProvince = _Paths.shopByProvince;
  static const shopByTerritory = _Paths.shopByTerritory;
  static const shopByStore = _Paths.shopByStore;
  static const tradesServices = _Paths.tradesServices;
  static const dealsAndOffers = _Paths.dealsAndOffers;
  static const searchServicesView = _Paths.searchServicesView;
  static const companyDetails = _Paths.companyDetails;
  static const contactUs = _Paths.contactUs;
  static const servicesView = _Paths.servicesView;
  static const chattingView = _Paths.chattingView;
  static const myOrders = _Paths.myOrders;
  static const companyAboutUsView = _Paths.companyAboutUsView;
  static const aboutUsView = _Paths.aboutUsView;
  static const changePasswordView = _Paths.changePasswordView;
  static const dataPrivacyView = _Paths.dataPrivacyView;
  static const editInformationView = _Paths.editInformationView;
  static const languageView = _Paths.languageView;
  static const supportView = _Paths.supportView;
  static const termsConditionsView = _Paths.termsConditionsView;
  static const completedOrdersView = _Paths.completedOrdersView;
  static const ongoingOrdersView = _Paths.ongoingOrdersView;
}

abstract class _Paths {
  _Paths._();
  static const home = '/home';
  static const splash = '/splash';
  static const onboarding = '/onboarding';
  static const login = '/login';
  static const signUP = '/signUP';
  static const forgotPassword = '/forgotPassword';
  static const verifyOtp = '/verifyOtp';
  static const resetPassword = '/resetPassword';
  static const bottomNav = '/bottomNav';
  static const messages = '/messages';
  static const saved = '/saved';
  static const category = '/category';
  static const profile = '/profile';
  static const searchProductView = '/searchProductView';
  static const recommendedProductView = '/recommendedProductView';
  static const trendingProductsView = '/trendingProductsView';
  static const searchLocation = '/searchLocation';
  static const productDetails = '/product-details';
  static const reviews = '/reviews';
  static const store = '/store';
  static const myCart = '/my-cart';
  static const checkoutView = '/checkoutView';
  static const checkoutSuccessfulView = '/checkoutSuccessfulView';
  static const notification = '/notification';
  static const shopByProvince = '/shop-by-province';
  static const shopByTerritory = '/shop-by-territory';
  static const shopByStore = '/shop-by-store';
  static const tradesServices = '/trades-services';
  static const dealsAndOffers = '/deals-and-offers';
  static const searchServicesView = "/searchServicesView";
  static const companyDetails = '/companyDetails';
  static const contactUs = '/contactUs';
  static const servicesView = '/servicesView';
  static const chattingView = '/chattingView';
  static const myOrders = '/myOrders';
  static const companyAboutUsView = '/companyAboutUsView';
  static const aboutUsView = '/aboutUsView';
  static const changePasswordView = '/changePasswordView';
  static const dataPrivacyView = '/dataPrivacyView';
  static const editInformationView = '/editInformationView';
  static const languageView = '/languageView';
  static const supportView = '/supportView';
  static const termsConditionsView = '/termsConditionsView';
  static const completedOrdersView = '/completedOrdersView';
  static const ongoingOrdersView = '/ongoingOrdersView';
}
